# Example annotated build data file
mod-name: ReStock
package:
  include-dependencies: true  # Include dependencies in the package
  included-gamedata:
    - ReStock
  included-support:  # Include these root-level files in packages
    - readme.txt
    - changelog.txt
    - license.txt
  extras-path: Distribution/RestockExtras/
  included-extras:
    - RestockRigidLegs
dependencies:  # Configure dependencies
  ModuleManager:
    version: 4.1.4
    location: s3
deploy:
  SpaceDock:
    enabled: true  # activate/deactivate this deployment script
    mod-id: 2098  # The Spacedock mod ID for deployment
  CurseForge:
    enabled: false  # activate/deactivate this deployment script
    mod-id: 230112  # The CurseForge mod ID for deployment
  GitHub:
    enabled: true  # activate/deactivate this deployment script
